version: 0.0
os: linux
files:
  - source: /spot_fleet
    destination: /home/ec2-user/spot_fleet
  # - source: scripts/script1.sh
  #   destination: /home/ec2-user/
  - source: scripts
    destination: /home/ec2-user/

permissions:
  - object: /home/ec2-user/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - file